# render.yaml
services:
  - type: web
    name: truenorthjobs
    env: python
    plan: starter
    region: oregon
    autoDeploy: true
    healthCheckPath: /
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app_05.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        value: jobs-index